fixes #14929 - fix foreman-installer due to kafo error
During vagrant installation of katello scenario, kafo would error with:

```
Running shell command: foreman-installer --scenario katello-devel
stty: standard input: Inappropriate ioctl for device
/usr/share/gems/gems/kafo-0.8.0/lib/kafo/progress_bars/colored.rb:19:in `finite_template':
  undefined method `>=' for nil:NilClass (NoMethodError)
  from /usr/share/gems/gems/kafo-0.8.0/lib/kafo/progress_bar.rb:19:in `initialize'
  from /usr/share/gems/gems/kafo-0.8.0/lib/kafo/kafo_configure.rb:120:in `new'
  from /usr/share/gems/gems/kafo-0.8.0/lib/kafo/kafo_configure.rb:120:in `execute'
  from /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:68:in `run'
  from /usr/share/gems/gems/clamp-1.0.0/lib/clamp/command.rb:133:in `run'
  from /usr/share/gems/gems/kafo-0.8.0/lib/kafo/kafo_configure.rb:156:in `run'
  from /sbin/foreman-installer:8:in `<main>'
```